language: julia
julia:
  - 1.3
  - 1.4
  - 1.5
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("ProtoBuf")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder());'
  - julia -e 'cd(Pkg.dir("ProtoBuf")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
